# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: ""
description: ""
markdown: kramdown
theme: cayman

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
